### ISSUE TITLE
ReferenceField will not be assigned or update is depth is set on serializer

### ISSUE THREAD

**Issue by hontrang** [hontrang/django#12]

**Comment by hontrang** [comment]
```
def to_internal_value(self, data):
        """
        Dict of native values <- Dict of primitive datatypes.
        """
        if not isinstance(data, Mapping):
            message = self.error_messages['invalid'].format(
                datatype=type(data).__name__
            )
            raise ValidationError({
                api_settings.NON_FIELD_ERRORS_KEY: [message]
            }, code='invalid')

        ret = OrderedDict()
        errors = OrderedDict()
        fields = self._writable_fields

        for field in fields:
            validate_method = getattr(self, 'validate_' + field.field_name, None)
            primitive_value = field.get_value(data)
            logger.debug('fieldname: {fn} - primitive_value: {pv} - validated method: {vm}'.format(fn=field.field_name, pv=primitive_value, vm=validate_method))
            try:
                validated_value = field.run_validation(primitive_value)
                if validate_method is not None:
                    validated_value = validate_method(validated_value)
            except ValidationError as exc:
                errors[field.field_name] = exc.detail
            except DjangoValidationError as exc:
                logger.error('Error message {exc}'.format(exc=exc))
            except SkipField:
                pass
            else:
                logger.debug('validated value is {vd}'.format(vd=validated_value))
                set_value(ret, field.source_attrs, validated_value)

        if errors:
            raise ValidationError(errors)

        return ret
```
data logger
```
DEBUG webapp.serializers fieldname: name - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: email - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: birdthday - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: password - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: firstName - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: lastName - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: avatar - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: returnItems - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: cartList - primitive_value: [{'_id': '5976138796279a33d08b29bc'}, {'_id': '5976138796279a33d08b29bf'}, {'_id': '5976138796279a33d08b29c2'}] - validated method: None
DEBUG webapp.serializers fieldname: favorite - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: created - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: level - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers fieldname: group - primitive_value: <class 'rest_framework.fields.empty'> - validated method: None
DEBUG webapp.serializers {}
```
validate_method always None

**Comment by hontrang** [comment]
- [ ]  http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers
- [ ]  https://github.com/encode/django-rest-framework/issues?q=is%3Aissue+Updating+nested+serializers+sort%3Aupdated-desc

**Comment by hontrang** [comment]
applying work around to force add update data to serializer by pass validating but get into new issue
```
ERROR django.request  Internal Server Error: /webapp/api/users/5978c52196279a9bdc562d32/
Traceback (most recent call last):
  File "d:\iot\angular\django\env\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "d:\iot\angular\django\env\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "d:\iot\angular\django\env\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "d:\iot\angular\django\env\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework\viewsets.py", line 86, in view
    return self.dispatch(request, *args, **kwargs)
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework\views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework\views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework\views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework\mixins.py", line 84, in partial_update
    return self.update(request, *args, **kwargs)
  File "D:\IoT\angular\django\backend\webapp\views.py", line 307, in update
    self.perform_update(serializer)
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework\mixins.py", line 80, in perform_update
    serializer.save()
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.update(self.instance, validated_data)
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework_mongoengine\serializers.py", line 269, in update
    instance = self.recursive_save(validated_data, instance)
  File "d:\iot\angular\django\env\lib\site-packages\rest_framework_mongoengine\serializers.py", line 262, in recursive_save
    instance.save()
  File "d:\iot\angular\django\env\lib\site-packages\mongoengine\document.py", line 321, in save
    self.validate(clean=clean)
  File "d:\iot\angular\django\env\lib\site-packages\mongoengine\base\document.py", line 402, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (Users:5978c52196279a9bdc562d32) (A ReferenceField only accepts DBRef, ObjectId or documents 1.A ReferenceField only accepts DBRef, ObjectId or documents 2.A ReferenceField only accepts DBRef, ObjectId or documents: ['cartList'])
```
**modify**
```
def to_internal_value(self, data):
        """
        Calls super() from DRF, but with an addition.
        Creates initial_data and _validated_data for nested
        EmbeddedDocumentSerializers, so that recursive_save could make
        use of them.
        If meets any arbitrary data, not expected by fields,
        just silently drops them from validated_data.
        """
        # for EmbeddedDocumentSerializers create initial data
        # so that _get_dynamic_data could use them
        for field in self._writable_fields:
            if isinstance(field, serializers.EmbeddedDocumentSerializer) and field.field_name in data:
                field.initial_data = data[field.field_name]
        ret = super(serializers.DocumentSerializer, self).to_internal_value(data)
        logger.debug('value - {} - {}'.format(__name__,ret))
        for k,v in data.items():
            ret[k] = v
        logger.debug('key: {}'.format(ret))
        # ret['cartList'] = data['cartList']
        # for EmbeddedDocumentSerializers create _validated_data
        # so that create()/update() could use them
        for field in self._writable_fields:
            if isinstance(field, serializers.EmbeddedDocumentSerializer) and field.field_name in ret:
                field._validated_data = ret[field.field_name]
        logger.debug(ret)
        return ret
```

check on mongoengine module

**Comment by hontrang** [comment]
Refer [link](https://github.com/MongoEngine/mongoengine/blob/009059def407b63db38c317258db1df88084e2eb/tests/test_dereference.py#L86)

**Comment by hontrang** [comment]
[Using the depth option on ModelSerializer will now create read-only nested serializers by default.](http://www.django-rest-framework.org/topics/3.0-announcement/)
Issue: 
```AssertionError: The `.create()` method does not support nested writable fields by default. Write an explicit `.create()` method for serializer `UserSerializer`, or set `read_only=True` on nested serializer fields.```

**Comment by hontrang** [comment]
[ListField validation](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L512)

**Comment by hontrang** [comment]
Work around for this case:
```
def to_internal_value(self, data):
        """
        Calls super() from DRF, but with an addition.
        Creates initial_data and _validated_data for nested
        EmbeddedDocumentSerializers, so that recursive_save could make
        use of them.
        If meets any arbitrary data, not expected by fields,
        just silently drops them from validated_data.
        """
        # for EmbeddedDocumentSerializers create initial data
        # so that _get_dynamic_data could use them
        for field in self._writable_fields:
            if isinstance(field, serializers.EmbeddedDocumentSerializer) and field.field_name in data:
                field.initial_data = data[field.field_name]
            if isinstance(field, drf.ListField) and field.field_name in data and hasattr(field, 'child'):
                child_data = field.get_value(data)
                li=[]
                for x in  range((len(child_data))):
                    j = ast.literal_eval(child_data[x])                    
                    d = field.child.get_value(ast.literal_eval(child_data[x]))
                    query = Products.objects.get(id=j['_id'])
                    li.append(query)
                    
        ret = super(serializers.DocumentSerializer, self).to_internal_value(data)
        # for EmbeddedDocumentSerializers create _validated_data
        # so that create()/update() could use them
        for field in self._writable_fields:
            logger.debug(field.field_name)
            if isinstance(field, serializers.EmbeddedDocumentSerializer) and field.field_name in ret:
                field._validated_data = ret[field.field_name]
            if isinstance(field, drf.ListField) and field.field_name in data and hasattr(field, 'child'):
                ret[field.field_name] = li
        return ret
```

**Comment by hontrang** [comment]
close as fixed
